#!/bin/bash

# javac -version
# javac 1.6.0_41

javac ex01_M1.java


# java -version
# java version "1.6.0_41"
# Java(TM) SE Runtime Environment (build 1.6.0_41-b02)
# Java HotSpot(TM) Server VM (build 20.14-b01, mixed mode)

java ex01_M1
